### ISSUE TITLE
Got " 'Window': #<Object> could not be cloned. " at web3auth.initModal()

### ISSUE THREAD

**Issue by brainwashed20** [Web3Auth/Web3Auth#114]
Hello,

I'm trying to integrate web3Auth Authentication within a VueJS Web App.

I'm using a custom clientId and I whitelisted the URLs that I want to access for the page. (http://localhost:8080 in my case)

Upon calling `await this.web3auth.initModal();` I get this error 
`openloginJrpc.esm.js?fd97:991 Uncaught DOMException: Failed to execute 'postMessage' on 'Window': #<Object> could not be cloned.
    at PostMessageStream._postMessage (webpack-internal:///./node_modules/@toruslabs/openlogin-jrpc/dist/openloginJrpc.esm.js:1026:24)
    at PostMessageStream._write (webpack-internal:///./node_modules/@toruslabs/openlogin-jrpc/dist/openloginJrpc.esm.js:165:10)
    at doWrite (webpack-internal:///./node_modules/@toruslabs/openlogin-jrpc/node_modules/readable-stream/lib/_stream_writable.js:409:139)
    at clearBuffer (webpack-internal:///./node_modules/@toruslabs/openlogin-jrpc/node_modules/readable-stream/lib/_stream_writable.js:526:7)
    at PostMessageStream.Writable.uncork (webpack-internal:///./node_modules/@toruslabs/openlogin-jrpc/node_modules/readable-stream/lib/_stream_writable.js:321:94)
    at PostMessageStream._onData (webpack-internal:///./node_modules/@toruslabs/openlogin-jrpc/dist/openloginJrpc.esm.js:127:14)
    at PostMessageStream.onMessage (webpack-internal:///./node_modules/@toruslabs/openlogin-jrpc/dist/openloginJrpc.esm.js:157:10)`

Do you have an idea on what is causing this issue ?

Thanks a lot!
Alexandru Gherghe

**Comment by brainwashed20** [comment]
Hello,

It happens on the following browser:

{"browser":{"name":"Chrome","version":"99.0.4844.83"},"os":{"name":"macOS","version":"10.15.7","versionName":"Catalina"},"platform":{"type":"desktop","vendor":"Apple"},"engine":{"name":"Blink"}}

**Comment by brainwashed20** [comment]
Also, Vue version is 3.0

**Comment by himanshuchawla009** [comment]
Seems like you are storing the web3auth instance using ref API.  Plz use it as a normal variable instead of ref.

**Comment by himanshuchawla009** [comment]
I have commented the solution above, feel free to reopen it if that doesn't helps. Closing it for now.
