### ISSUE TITLE
Vue3 is not compatible for web3auth 

### ISSUE THREAD

**Issue by KawabataLemon** [Web3Auth/Web3Auth#29]
just create vue3 project (via Vite) and add following codes.

```

import { Web3Auth } from "@web3auth/web3auth"
import { CHAIN_NAMESPACES } from "@web3auth/base"

const web3auth = new Web3Auth({
  chainConfig: { chainNamespace: CHAIN_NAMESPACES.EIP155 },
  clientId: "815138507228-0qmlub6bcdroj6jc7qam40g87gclmohn.apps.googleusercontent.com"
})

await web3auth.initModal();

```

then, error occured

```
_stream_readable.js:48 Uncaught ReferenceError: global is not defined
    at node_modules/@toruslabs/openlogin-jrpc/node_modules/readable-stream/lib/_stream_readable.js (_stream_readable.js:48:21)
    at __require2 (chunk-SULJOONQ.js?v=767cbc63:48:44)
    at node_modules/@toruslabs/openlogin-jrpc/node_modules/readable-stream/readable-browser.js (readable-browser.js:1:28)
    at __require2 (chunk-SULJOONQ.js?v=767cbc63:48:44)
    at defineProperty.js:13:10
```

Is there any workaround?

**Comment by himanshuchawla009** [comment]
Hi you need to add node browser polyfills in your vite config, plz refer to this example here: https://github.com/himanshuchawla009/web3auth-vite-sample

**Comment by KawabataLemon** [comment]
thank you for helping ! very useful example!
