### ISSUE TITLE
Error: Cannot find module '@babel/plugin-syntax-bigint' when building project

### ISSUE THREAD

**Issue by goosecoid** [Web3Auth/Web3Auth#82]
# Steps

1.  Cloned repo
2. `npm run bootstrap`
3. `npm run build`

First error: 

```shell
lerna notice cli v4.0.0
lerna info Executing command in 13 packages: "yarn run build"
@web3auth/base: yarn run v1.22.17
@web3auth/base: $ rimraf dist/ && torus-scripts build
@web3auth/base: /bin/sh: torus-scripts: command not found
@web3auth/base: error Command failed with exit code 127.
@web3auth/base: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 127 in '@web3auth/base'
```

4. `npm i -g @toruslabs/torus-scripts`
5. `npm run build`

```shell
$ rimraf dist/ && torus-scripts build
@web3auth/base: /Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/plugins.js:139
@web3auth/base:   throw error;
@web3auth/base:   ^
@web3auth/base: Error: Cannot find module '@babel/plugin-syntax-bigint'
@web3auth/base: Require stack:
@web3auth/base: - /Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/plugins.js
@web3auth/base: - /Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/index.js
@web3auth/base: - /Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/index.js
@web3auth/base: - /Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/config/rollup.config.js
@web3auth/base: - /Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/scripts/build.js
@web3auth/base:     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:885:15)
@web3auth/base:     at resolve (internal/modules/cjs/helpers.js:94:19)
@web3auth/base:     at tryRequireResolve (/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/plugins.js:157:9)
@web3auth/base:     at resolveStandardizedNameForRequrie (/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/plugins.js:195:19)
@web3auth/base:     at sync (/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/plugins.js:224:12)
@web3auth/base:     at sync (/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/gensync/index.js:182:19)
@web3auth/base:     at /Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/gensync/index.js:210:24
@web3auth/base:     at Generator.next (<anonymous>)
@web3auth/base:     at resolvePlugin (/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/plugins.js:83:17)
@web3auth/base:     at resolvePlugin.next (<anonymous>) {
@web3auth/base:   code: 'MODULE_NOT_FOUND',
@web3auth/base:   requireStack: [
@web3auth/base:     '/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/plugins.js',
@web3auth/base:     '/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/config/files/index.js',
@web3auth/base:     '/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/node_modules/@babel/core/lib/index.js',
@web3auth/base:     '/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/config/rollup.config.js',
@web3auth/base:     '/Users/adrienblavier/.nvm/versions/node/v14.17.0/lib/node_modules/@toruslabs/torus-scripts/scripts/build.js'
@web3auth/base:   ]
@web3auth/base: }
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@web3auth/base'
```

As you can see I run node v14.17.0. Anything obvious I am missing here?

**Comment by himanshuchawla009** [comment]
correct commands are:-

```
npm i -g yarn

yarn
yarn run bootstrap
yarn run build

```

**Comment by himanshuchawla009** [comment]
closing it, feel free to reopen if above commands doesn't works

**Comment by goosecoid** [comment]
Thanks for the quick response. Works now!
